---
###################################################################################
# GitHub workflow to automatically create a PR against 'main' branch,
# when there is a PR on 'rel-*' branch created.
#
# 1. It checks if the PR already exist and if so, does not create one.
# 2. In future we can enhance it to read the branch name from Jira label or
#    equivalent and then create PR. This way we can extend it to multiple
#    forward merges.
###################################################################################
name: Create tag on release branch
on:
  pull_request:
    types: [closed]
    branches:
      - 'rel-*'
      - 'main'

jobs:
  create-tag-on-merge:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Find latest tag
        run: |
          latest_tags+=("$(git tag --contains '${{ github.event.pull_request.base.sha }}')")
          for tag in $latest_tags; do tag_arr+=($tag); done
          echo "TAGS=${tag_arr[@]}" >> $GITHUB_ENV
        id: latest_tag

      - name: Create tag and update ref
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PIPELINES_REPO_TOKEN  }}
          script: |
            latest_tag = '0.0.0'

            // process multiple tags if any
            tags = "${{ env.TAGS }}".split(' ')
            if (tags.length == 1) {
              latest_tag = tags[0]
            } else {
              tag0 = tags[0].split('.')
              tag1 = tags[1].split('.')

              // only if multiple tag is present in 'main' branch, then we want to take the tag with greater major version
              if ((parseInt(tag0[1]) > parseInt(tag1[1])) && ("${{ github.event.pull_request.base.ref }}" == 'main')) {
                latest_tag = tags[0]
              } else {
                latest_tag = tags[1]
              }
            }

            console.log("Latest tag: " + latest_tag)

            // check if we have
            if ( latest_tag == '' || latest_tag === undefined) {
              console.log("Couldn't determine the latest tag, exiting. Retry manually..")
              process.exit(1);
            }

            // increase the minor version lineraly to get the new tag
            tag_parts = latest_tag.split('.')
            new_tag = [tag_parts[0], tag_parts[1], parseInt(tag_parts[2]) + 1].join('.')

            // head of the branch needs to be tagged
            sha_to_tag = "${{ github.event.pull_request.merge_commit_sha }}"

            console.log("Creating tag: " + new_tag + " against commit " + sha_to_tag)

            result = await github.git.createTag({
                owner: "${{ github.repository_owner }}",
                repo: "${{  github.repository }}".split('/')[1],
                tag: new_tag,
                message: 'Tag created by CI pipeline',
                type: 'commit',
                object: sha_to_tag
            });

            console.log(result)

            fullTagName = "refs/tags/" + new_tag

            console.log("Updating tag with REF: " + fullTagName)

            newRef = await github.git.createRef({
                owner: "${{ github.repository_owner }}",
                repo: "${{  github.repository }}".split('/')[1],
                ref: fullTagName,
                sha: sha_to_tag
            });

            console.log('Ref updated.');
            core.setOutput('tag_ref', fullTagName)
