# This is a basic workflow to help you get started with Actions
name: Tessell Pipelines Code Build

# Controls when the workflow will run
on:
  push:
    branches:
      - 'main'
      - 'rel-*'
      - 'TS-*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  gradle-build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      NEXUS_PULL_REPOS_M2: tessell-m2-development
      NEXUS_PUSH_REPOS_M2: tessell-repos-m2-component


    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Get branch name
        shell: bash
        run: |
          echo "SOURCE_BRANCH=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV

      - name: Set Pull repository
        if: ${{ startsWith(env.SOURCE_BRANCH,'rel-') || env.SOURCE_BRANCH == 'main' }}
        shell: bash
        run: |
          echo "NEXUS_PULL_REPOS_M2=tessell-m2-component" >> $GITHUB_ENV

      - name: Build
        if: ${{ !startsWith(env.SOURCE_BRANCH,'rel-') && env.SOURCE_BRANCH != 'main' }}
        run: |
          ./gradlew mavenPackage --console plain \
            -Pnexus_push_username="${{ secrets.CIPIPELINE_NEXUS_USERNAME }}" \
            -Pnexus_push_password="${{ secrets.CIPIPELINE_NEXUS_PASSWORD }}" \
            -Pnexus_username="${{ secrets.CIPIPELINE_NEXUS_USERNAME }}" \
            -Pnexus_password="${{ secrets.CIPIPELINE_NEXUS_PASSWORD }}"

      - name: Build with Gradle
        if: ${{ startsWith(env.SOURCE_BRANCH,'rel-') || env.SOURCE_BRANCH == 'main' }}
        run: |
          ./gradlew mavenDeploy --console plain \
            -Pnexus_push_username="${{ secrets.CIPIPELINE_NEXUS_USERNAME }}" \
            -Pnexus_push_password="${{ secrets.CIPIPELINE_NEXUS_PASSWORD }}" \
            -Pnexus_username="${{ secrets.CIPIPELINE_NEXUS_USERNAME }}" \
            -Pnexus_password="${{ secrets.CIPIPELINE_NEXUS_PASSWORD }}" \
            -Pnexus_push_repo_m2="${{ env.NEXUS_PUSH_REPOS_M2 }}" \
            -Pnexus_pull_repo_m2="${{ env.NEXUS_PULL_REPOS_M2 }}"
